### ISSUE TITLE
remove original_image

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/imsanity#13]
For new uploads, we already prevent the original_image from being stored because we resize prior to WP's scaling process.
But during the bulk resizer, the original_image is left around, wasting disk space. And since our primary goal in Imsanity is saving disk space, this is less than ideal.
Ideas:

- Have a tool to clean all originals
- Remove original during bulk resizing
- Use original, rather than scaled version, to create new image during bulk resizing

**Comment by HandyGadget** [comment]
Still it might be useful to have a switchable option to delete the original file once imsanitised and help those who are trying to save space on their server and prevent oversize backup issues.

**Comment by sneader** [comment]
As a hosting provider, we've seen a large uptick of clients that are exceeding their disk quota, due to the new feature in WP 5.3 that created additional "scaled" versions of large images, but leaves the overly large image on the server. We highly recommend Imsanity for new WP installs, but the current version does not help much for existing installs that have already been "WP 53 scaled".  Thus we would absolutely LOVE the idea of a new feature in Imsanity to handle this problem. Even if the originals could be resized, it would help. Removing them entirely (since they have been scaled and the scaled versions are now on the website) would be better but maybe less safe?  Thank you for your help!!

**Comment by laxbobber** [comment]
I agree with both commenters here. Having it be an option would be great, especially for sites that have some "history" which needs cleaning up.

**Comment by thomasmalley** [comment]
This would be so great 😻 for exactly the same reasons @sneader mentioned above. 
i.E. our hosting provider disables backups after a certain disk quota is exceeded. We just recently discovered the full potential of this great plugin. Deleting or moving the large Originals into a custom Folder within _wp-content_ which can then be archived or deleted would be so nice!

**Comment by kkri** [comment]
Yes, storing the original images in a specific folder or, better, creating an"original images list" where selecting single or multiple or bulk images, it will be possible to delete or backup them in local devices or so, will be very useful. Thanx

**Comment by nosilver4u** [comment]
Just checked code into master branch, will be released with 2.7.
There is an option to remove the originals, which applies to the revamped bulk process and the new selective resizing option in the Media Library's List View. Additionally, the Imsanity column in List View will allow one to selectively remove originals for already-resized images.
