### ISSUE TITLE
undefined property $imsanity_deep_scan

### ISSUE THREAD

**Issue by cfoellmann** [nosilver4u/imsanity#4]
SEE: https://wordpress.org/support/topic/bug-undefined-property-imsanity_deep_scan/

Tested on WP Multisite 5.0.3 with 2.4.2

Error still comes up on network admin page on submit.

```

Notice | Undefined index: imsanity_deep_scan | 1 | -do_action('admin_init')wp-admin/admin.php:156imsanity_register_settings()wp-includes/class-wp-hook.php:286imsanity_network_settings_update()wp-content/plugins/imsanity/settings.php:420wp-content/plugins/imsanity/settings.php:330 | Plugin: imsanity
-- | -- | -- | -- | --


```

**Comment by nosilver4u** [comment]
That appears to be a slightly different issue than the original, which indicates that perhaps the settings page has an error.

**Comment by cfoellmann** [comment]
the original error posted on wp.org references the same file and might be the same line (depending on the version line number might have changed)

**Comment by nosilver4u** [comment]
It IS the same file and same line, but the original one was "undefined property" because the settings object had not been properly initialized. This one is "undefined index" which has something to do with the $_POST value being assigned to the settings object. I just replicated it myself, now to track it down!

**Comment by nosilver4u** [comment]
Apparently, an empty checkbox does not get submitted via POST, so the logic had to be tweaked a bit. Fixed in latest commit.
