### ISSUE TITLE
Rethink options

### ISSUE THREAD

**Issue by cfoellmann** [nosilver4u/imsanity#5]
First @nosilver4u I really love your work and all my posting is just to contribute and help improve what is already great!

Points to review:

- [x] evaluate merging values into array in one/two options
- [x] check autoload status of all options

- [x] if multisite allows for individual settings per site make network settings the defaults

**Comment by nosilver4u** [comment]
The first is something I've seen from many other plugins, but it makes it more difficult to work with, and doesn't really improve much. In fact, it makes it harder to deal with the autoload status, and THAT is definitely something I should review.

On the last point, I think I understand what you're getting at, but let me confirm that. Rather than fall back to the Imsanity defaults when a setting has not been configured for a particular site, you'd rather it fall back to the network-configured options, right?

**Comment by cfoellmann** [comment]
1. i think it makes dealing with is easier but it is not really important to me
2. yes. All options not meant for frontend rendering needs to be Autoload false
3. You understood right. First best iteration would be to set the network setting as defaults. Improvement on that would be a switch to allow the site admin to activate the per site overwrites

**Comment by nosilver4u** [comment]
Latest commits include prevention of auto-loading and use of network settings as single-site defaults.
If plugin is activated network-wide, and per-site config is allowed, the defaults will be defined the first time one visits the single-site admin.
Otherwise, defaults are defined when activating the plugin on each single site.

Additionally, due to the way the network settings were already implemented, one can now activate the plugin on any single-site, and then disable per-site configuration at the network level to use the network settings globally without network-wide activation. So if one wants global configuration, but not global activataion, Imsanity will allow that just fine.
