### ISSUE TITLE
Extended network support

### ISSUE THREAD

**Issue by cfoellmann** [nosilver4u/imsanity#7]
- [x] Allow activation on blog_id = 1

- [ ] tabbed network settings page

  - [ ] `permissions` - set who can admin on a blog/subsite, defaults vs enforcement

  - [ ] `defaults` - select default settings

Work-in-progress #8

**Comment by cfoellmann** [comment]
@nosilver4u what do you think about classes and namespaces?
I would like to create a class for the settings and extend on that one for the network settings!

**Comment by nosilver4u** [comment]
I don't know that allowing activation on blog 1 should enable network settings. From a permissions stand-point, I think it's okay, because you're not letting blog 1 define network settings, but letting the network admin configure global settings if they want to go that route.
However, I'm not sure I see the benefit, and it could complicate the logic needed. Are there other plugins that do this?

Do we have enough settings to go for a tabbed layout? Seems a little unnecessary, but that's my 2 cents.

Now permissions, that definitely needs to change, saw your fix in the pull request, and I definitely think that should be fixed. One idea that could be implemented though, is to allow folks to override the permissions by filter, like we do in EWWW IO.

And I do think it's a nice idea to allow network admins to set defaults that the sub-sites will use, rather than always using the hard-coded defaults for sub-sites. Perhaps this is why you suggested showing network settings when active on blog=1? Still curious if there are other plugins doing this sort of thing.

As for namespaces, I haven't dealt much with those, but I have absolutely nothing against using classes, I've been slowly converting EWWW IO to use classes, and pretty much all new features go into their own classes. So that's definitely open for possibility if you think it will help make the code simpler/cleaner.

Please keep the single-site settings using standard WP options values though, I don't want those in a single array/option. It makes it impossible to view them in the database. It was actually on my todo list to move the network settings into regular network options also, but if you want to keep those in an array/object I won't object. Pun not intended, but it made be chuckle :)
Anyway, it would be nice to move the multisite settings into the wp_sitemeta table rather than maintaining our own table just for 2 rows.

Regarding pull request #8 I've generally not allowed for translation of the plugin name. In this case, it seems a bit weird when it isn't even technically an English word. Seems like it would be difficult for translators, and they'd probably just copy it through, no?

**Comment by nosilver4u** [comment]
Also, I hope I don't come across too argumentative. I really don't have a lot of time to spend on Imsanity, so this makes me incredibly grateful that you would be interested in contributing to the plugin, but also a little guarded on spending too much time chasing rabbits :)
I look forward to any improvements that can be made to help folks keep their image sizes in check!

**Comment by cfoellmann** [comment]
FIRST: I really appreciate you spending your time discussing this with me. I am really happy to contribute and I respect your position as the "product owner".
Putting up all the arguments now saves us both time in the long run. I put out what I want to and how to do it. You put against this your opinions and insights. We meet in the middle and no ones time is wasted.
AND I like you writing where you stand in clear words!!

Lets get to the topic at hand:

```
I don't know that allowing activation on blog 1 should enable network settings.
```
There is no other way to give the admin an UI to set up the defaults for blogs activated later.
Situation is that "you" will add sites over time and you can not set defaults AND NOT force the plugin on all pages. (network wide activation is more or less final.

```
Are there other plugins that do this?
```
This is more or less the way "everyone" is doing it. Yoast, Perfmatters, Stream come to mind. Can look for more....

```
Do we have enough settings to go for a tabbed layout? Seems a little unnecessary, but that's my 2 cents.
```
I like to split it up but it is not a must.

```
Now permissions, that definitely needs to change, saw your fix in the pull request, and I definitely think that should be fixed. One idea that could be implemented though, is to allow folks to override the permissions by filter, like we do in EWWW IO.
```
Yes. adding a filter like this https://github.com/wp-cloud/wpmu-plugin-manager/blob/develop/wpmu-plugin-manager.php#L91
and (later) add an option to change the permission in the UI (network-wide or even more complex `per site`)

```
And I do think it's a nice idea to allow network admins to set defaults that the sub-sites will use, rather than always using the hard-coded defaults for sub-sites. Perhaps this is why you suggested showing network settings when active on blog=1? Still curious if there are other plugins doing this sort of thing.
```
See point 1

```
As for namespaces, I haven't dealt much with those, but I have absolutely nothing against using classes, I've been slowly converting EWWW IO to use classes, and pretty much all new features go into their own classes. So that's definitely open for possibility if you think it will help make the code simpler/cleaner.
```
Great. I will have a look at EWW to see what your style is and if I can replicate it in a way.

```
Please keep the single-site settings using standard WP options values though, I don't want those in a single array/option. It makes it impossible to view them in the database. 
```
Like I already said: I am fine with that!!

```
It was actually on my todo list to move the network settings into regular network options also, but if you want to keep those in an array/object I won't object. Pun not intended, but it made be chuckle :)
```
😈 We can decide when I get there.

```
Anyway, it would be nice to move the multisite settings into the wp_sitemeta table rather than maintaining our own table just for 2 rows.
```
Would make it efficient but would also require WP >= 5.1 which might be too limiting a the moment.

```
Regarding pull request #8 I've generally not allowed for translation of the plugin name. In this case, it seems a bit weird when it isn't even technically an English word. Seems like it would be difficult for translators, and they'd probably just copy it through, no?
```
I would suggest letting me fix everything up for proper translations. I am more or less a "pro" in that regard. Done it a lot.
Anything output as strings should be translatable. Think about languages non-arabic languages which rewrite even names.

**Comment by nosilver4u** [comment]
Just wanted to mention 2 quick things, I'll re-read it again on Monday and respond more fully then.

Regarding the wp_sitemeta table, that's been in WP a long time, if not since WPMU was merged into core. Specifically, I was meaning that Imsanity ought to use this function: https://developer.wordpress.org/reference/functions/update_site_option/
There is the newer update_network_option(), so if you wanted to go that route instead, I've no qualms either way.

As for code style, I'm not particularly elegant in my code, but I do follow the WPCS Core & Docs rulesets for PHP (my JS is not particularly consistent, and I've never attempted to validate that): https://github.com/nosilver4u/imsanity/blob/master/phpcs.ruleset.xml

**Comment by cfoellmann** [comment]
ping 😉 

lets create a roadmap for this so I can start working on this.

**Comment by nosilver4u** [comment]
Okay, what do you think about this:
1. Add the permissions override via filter.
2. Fix the translation issues.
3. Activate network-wide settings when activated on blog=1.
4. Make it so that the network settings are the defaults for each sub-site that activates the plugin.
5. Add the permissions override in the network admin GUI (maybe even on single-site, not sure about that).

When in 3, there should probably be some indication on the network settings that they aren't overriding single-site settings, but rather setting defaults for new sites.
That would likely depend on the value of the "allow each site to configure..." option.

So when "allow each site..." is enabled, we should indicate that they are setting defaults, and any changes will not trickle down to sites that already have their own config, since that's the way it already operates. The "allow each site..." option could thus be enabled by default in 3.

Wanted to confirm the wp_sitemeta table IS actually the typical Network options storage space. I saw the  new feature about site metadata in the 5.1 release notes, and that is stored in a new wp_blogmeta table. Not confusing at all, right? :smile:

**Comment by nosilver4u** [comment]
Oh, and we can set our defaults something like this, instead of via constant:
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/unique.php#L115
That is triggered during the upgrade routine, run on admin_init: https://github.com/nosilver4u/ewww-image-optimizer/blob/master/common.php#L501
Pretty sure we already have an "upgrade routine" in Imsanity

The single-site ones can be added using add_site_option() technically, but only if we don't want them autoloaded, which is probably the case for the Imsanity settings. I don't think we have anything that should load on a front-end request.

Imsanity's admin_init hook is here: https://github.com/nosilver4u/imsanity/blob/master/settings.php#L407
And we can detect when an upgrade is happening by using IMSANITY_VERSION

**Comment by nosilver4u** [comment]
I was working through some more of this, and I think I had it over-complicated in my mind.
At this point, I think the best implementation is to let the network settings set the defaults for a new site on activation of the plugin. Thus, once Imsanity is active on a single site, the network settings will be applied once, and then the site will operate independently.
I believe that aligns with what you had given as the use case, but just wanted to get that written down for now.

**Comment by nosilver4u** [comment]
Okay, all is implemented except a UI for altering the permissions required for Imsanity configuration (item 5 of my list above). I'm not going to expose that currently, as it's too open-ended with over 50+ default capabilities, and since roles/capabilities can be extended infinitely. It's much better as a filter that can be implemented by advanced users, since it would indeed be an advanced use-case (allowing roles that can't manage_options to actually manage options...).
